version: '3'

tasks:
#  gin-types:
#    cmds:
#      - oapi-codegen --package=dto  --generate types ../../docs/procrastination_proxy> internal/routes/handlergen.go
#    silent: false

  gin-handlers:
    cmds:
       - oapi-codegen --package=docs  --generate types,client docs/procastination_proxy.yaml > openapi.gen.go
#      - oapi-codegen --package=handlers --generate gin docs/procrastination_proxy> internal/routes/handlers/handler.gen.go
    silent: false

