name: CI-Builds

on:
  push:
    branches: [develop]

jobs:
  Build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: password
          POSTGRES_DB: everyshilling
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      #setting up build for GO
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
        id: go

      - name: checkout code into Go module directory
        uses: actions/checkout@v2

        #- name: install dependencies
        # run: go mod download

  Test:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Test Go Service
        run: go mod init github.com/MikeMwita/procastination_proxy

  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Deploying..."